config/routes.rb
CalPlusPlus::Application.routes.draw do
  root :to => 'main#welcome'
  get 'home' => 'main#home'

  # resources :users, :only => [ :show, :edit, :update ]
  post '/oauth/request_token' => 'sessions#new'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/login' => 'main#welcome'
  match '/logout' => 'sessions#destroy', :as => :logout

  match '/import' => 'import#list'
  get '/import/list'
  get '/import/calendar'
  get '/import/train'
  get '/import/open'
  get '/import/save'

  resources :events

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? 'success' : 'error' %>">
            <a class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="sidebar">
    <div class="nav">
        <div class="row-fluid">
            <a href="<%= root_path %>" target="_self">
                <img src="/images/logo.png" alt="cal++ logo" width='300px'>
            </a>
        </div>
        <% if @user %>
            <span>Welcome <%= @user.name %>!</span>
            <br>
            <%= link_to 'Import Calendar', import_path, :class => 'btn btn-primary' %>
            <%= link_to 'Logout', logout_path, :class => 'btn btn-danger' %>
            <br>
            <br>
        <% end %>
        <p>
            Here at Cal++, we believe calendars should be easy on the eyes and minds.
            We prioritize your events are important or not. Simple as that.
            We use a Bayesian machine learning algorithm to understand and analyze which events are important.
            Of course, you can always let us know what's important by marking your events manually.
        </p>

        <p style="text-align:center;">&#169 2013. Zurawicki, Chang, and Liu.<br>CS51 2013 Final Project </p>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : 'Cal++' %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'App_Name' %>">
    <%= stylesheet_link_tag 'docs', 'bootstrap', 'application', 'jquery-ui-1.8.13.custom', 'jquery.qtip', 'fullcalendar', 'bootstrap-responsive', :media => 'all' %>
    <%= javascript_include_tag 'http://code.jquery.com/jquery-1.6.3.js', 'jquery-ui-1.8.13.custom.min', 'fullcalendar.min', 'underscore', 'backbone', 'jquery.qtip-1.0.0-rc3.min', 'datetime', 'date', 'date_time', 'application' %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-36903095-1']);
        _gaq.push(['_setDomainName', 'calplusplus.com']);
        _gaq.push(['_setAllowLinker', true]);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script');
            ga.type = 'text/javascript';
            ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <%= render 'layouts/navigation' %>
        </div>

        <div role="main" class="span9">
            <%= render 'layouts/messages' %>
            <%= yield %>
        </div>
    </div>
</div>
</body>
</html>